services:
  discord-bot:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        PHP_VERSION: '8.4-bookworm'
      target: "${BUILD_TARGET:-app}"
    container_name: discord-bot
    tty: true
    stdin_open: true
    volumes:
      - ./:/var/www/app
    networks:
      - my-shared-network

networks:
  my-shared-network:
    external: true